name: 🕷️ Repo Crawler

on:
  workflow_dispatch:
  # Run job At 08:00 on every day-of-week from Monday through Friday.
  schedule:
              # https://crontab.guru/
              #   ┌───────────── minute (0 - 59)
              # │ ┌───────────── hour (0 - 23)
              # │ │ ┌───────────── day of the month (1 - 31)
              # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
              # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
              # │ │ │ │ │
              # │ │ │ │ │
              # │ │ │ │ │
              # * * * * *
    - cron:  '0 8 * * 1-5'

jobs:
  crawl_repo:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: ⚡️ Invoke Repo Crawler Function Lambda
        id: lambdaInvocation
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: ${{ github.event.repository.name }}-prod-crawlRepository
          # Payload: '{ "myParameter": false }'

      - name: 📝 Store response payload to file
        if: always()
        run: echo '${{ fromJSON(steps.lambdaInvocation.outputs.response).Payload }}' > invocation-response.json

      - name: ⬆️ Upload Lambda output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lambda-output
          path: invocation-response.json