name: 🕷️ Repo Crawler

on:
  workflow_dispatch:
  # Run job At 08:00 on every day-of-week from Monday through Friday.
  schedule:
              # https://crontab.guru/
              #   ┌───────────── minute (0 - 59)
              # │ ┌───────────── hour (0 - 23)
              # │ │ ┌───────────── day of the month (1 - 31)
              # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
              # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
              # │ │ │ │ │
              # │ │ │ │ │
              # │ │ │ │ │
              # * * * * *
    - cron:  '0 8 * * 1-5'

jobs:
  crawl_repo:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: ⚡️ Invoke Repo Crawler Function Lambda
        id: lambdaInvocation
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: ${{ github.event.repository.name }}-prod-crawlRepository
          # Payload: '{ "myParameter": false }'

      - name: 📝 Store response payload to file
        if: always()
        run: echo '${{ fromJSON(steps.lambdaInvocation.outputs.response).Payload }}' > invocation-response.json

      - name: ⬆️ Upload Lambda output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lambda-output
          path: invocation-response.json

  email_notification:
    needs: [crawl_repo]
    name: "🔔 Send Email Notification"
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
      
    steps:
      - name: 🔊 Send conditional failure mail
        if: ${{ needs.crawl_repo.result == 'failure' }}
        uses: dawidd6/action-send-mail@v3.7.0
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ❌ (FAILURE) Open Source Crawler Workflow
          # email body as text
          body: |
            ❌ Web Crawler failed for: Open Source Crawler Workflow

            Possible failures include:
              - GitHub Actions
              - Lambda function
              - Redis database

            ---------

            ℹ️ Repository: https://github.com/open-source-crawler
            🤖 Workflow: https://github.com/spencerlepine/open-source-crawler/actions/runs/${{ github.run_id }}
          # comma-separated string, send email to
          to: spencerlepine26@gmail.com
          # from email name
          from: SpencerBot