name: 🧐 Repo Analyzer

on:
  workflow_dispatch:
  # Run job At 08:15 on every day-of-week from Monday through Friday.
  schedule:
              # https://crontab.guru/
              #   ┌───────────── minute (0 - 59)
              # │ ┌───────────── hour (0 - 23)
              # │ │ ┌───────────── day of the month (1 - 31)
              # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
              # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
              # │ │ │ │ │
              # │ │ │ │ │
              # │ │ │ │ │
              # * * * * *
    - cron:  '15 8 * * 1-5'

jobs:
  fetch_repo_url:
    runs-on: ubuntu-latest
    name: "☁️ Fetch URL From AWS"
    if: github.ref == 'refs/heads/main'
    outputs:
      repoUrl: ${{ steps.lambdaOutputExtraction.outputs.repoUrl }}

    steps:
      - name: ⚡️ Invoke Repo Analyzer Function Lambda
        id: lambdaInvocation
        uses: gagoar/invoke-aws-lambda@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FunctionName: ${{ github.event.repository.name }}-prod-fetchAnalyzeRepoQueue
          # Payload: '{ "myParameter": false }'

      - name: 📝 Store response payload to file
        if: always()
        run: echo '${{ fromJSON(steps.lambdaInvocation.outputs.response).Payload }}' > invocation-response.json

      - name: ⬆️ Upload Lambda output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lambda-output
          path: invocation-response.json

      - name: ✂️ Extract repository URL from previous step
        if: always()
        run: echo ::set-output name=repoUrl::$(cat invocation-response.json | jq . | jq .body.repoUrl | tr -d '"' 2>&1)
        id: lambdaOutputExtraction
  
  security_scan:
    needs: [fetch_repo_url]
    name: "🛡️ Security Scan"
    runs-on: ubuntu-latest
    if: ${{ needs.fetch_repo_url.outputs.repoUrl }} && github.ref == 'refs/heads/main'
    env:
      REPO_URL: ${{ needs.fetch_repo_url.outputs.repoUrl }}
      
    steps:
      - name: ⬇️ Checkout external repository
        if: ${{ env.REPO_URL }}
        id: checkout-external-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_URL }}
      
      - name: ✏️ Initialize analysis report
        run: |
          mkdir security
          cd security
          mkdir codeql
          mkdir SCAN
          cd ..
      
      - name: 🛠️ Initialize CodeQL
        if: steps.checkout-external-repo.outcome == 'success' && steps.checkout-external-repo.conclusion == 'success'
        uses: github/codeql-action/init@v2
        with:
          debug: true
      
      - name: 🏗️ Autobuild Repo Code
        if: steps.checkout-external-repo.outcome == 'success' && steps.checkout-external-repo.conclusion == 'success'
        uses: github/codeql-action/autobuild@v2

      - name: ✅ Perform CodeQL Analysis
        if: always() && steps.checkout-external-repo.outcome == 'success' && steps.checkout-external-repo.conclusion == 'success'
        id: codeql-analysis
        uses: github/codeql-action/analyze@v2
        with:
          upload: "false"
          add-snippets: "true"
          output: "../results"

      - name: 📁 Move CodeQL results into output folder
        if: always() && steps.codeql-analysis.outcome == 'success' && steps.codeql-analysis.conclusion == 'success'
        run: cp -a ../results/. ./security/codeql
        
      # Alternate code scan
      # https://github.com/marketplace/actions/security-and-licence-scan
      # NOTES:
      #   - This action needs to be provided with a link to the target repository
      #   - When WORKSPACE is set, it can auto-build the source code
      #   - When WORKSPACE is set, it can auto-detect the languages as well
      #   - It will scan the dependencies and code from there
      
      - name: ✅ Perform SCAN Analysis
        if: always() && steps.checkout-external-repo.outcome == 'success' && steps.checkout-external-repo.conclusion == 'success'
        id: scan-analysis
        uses: ShiftLeftSecurity/scan-action@master
        # with:
        #   src: ${{ env.REPO_URL }} NOT WORKING
        env:
          WORKSPACE: https://github.com/${{ env.REPO_URL }}
          SCAN_AUTO_BUILD: true
          
      - name: 📁 Move SCAN results into output folder
        if: always() && steps.scan-analysis.outcome == 'success' && steps.scan-analysis.conclusion == 'success'
        run: cp -a ./reports/. ./security/SCAN

      - name: ⬆️ Upload security scan results
        if: always() && (steps.scan-analysis.outcome == 'success' || steps.codeql-analysis.conclusion == 'success')
        uses: actions/upload-artifact@v3
        with:
          name: security
          path: security
  
  # Preform typo scan
  # https://github.com/crate-ci/typos
  # https://crates.io/crates/typos-cli
  typo_scan:
    needs: [fetch_repo_url]
    name: "🚫 Typo Scan"
    runs-on: ubuntu-latest
    if: ${{ needs.fetch_repo_url.outputs.repoUrl }} && github.ref == 'refs/heads/main'
    env:
      REPO_URL: ${{ needs.fetch_repo_url.outputs.repoUrl }}
      
    steps:
      - name: ⬇️ Checkout external repository
        if: ${{ env.REPO_URL }}
        id: checkout-external-repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_URL }}
      
      - name: ✏️ Initialize analysis report
        run: |
          mkdir typos
          cd typos
          touch typos.txt
          touch typos-diff.md
          cd ..
      
      - name:  🛠️ Configure rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 🛠️ Configure rust cargo (package manager)
        if: always()
        uses: actions-rs/cargo@v1
    
      - name: 📦 Install spell-checker dependency
        run: cargo install typos-cli
        
      - name: 🛠️ Create spell checker config file
        run: |
          touch _typos.toml
          echo "[files]" >> _typos.toml
          echo "extend-exclude = ['typos/**', 'public/**']" >> _typos.toml

      - name: 🚫 Preform typo scan
        id: typo-scan
        run: |
          echo '## Detected Typos' >> typos/typos.txt
          ${{ github.workspace }}/../../../.cargo/bin/typos >> typos/typos.txt || true
          echo '## Detected Typos Diff' >> typos/typos-diff.md
          echo '```diff' >> typos/typos-diff.md
          ${{ github.workspace }}/../../../.cargo/bin/typos --diff >> typos/typos-diff.md || true
          
      - name: ⬆️ Upload typo scan results
        uses: actions/upload-artifact@v3
        with:
          name: typos
          path: typos

  finalize_report:
    needs: [fetch_repo_url, security_scan, typo_scan]
    name: "📝 Finalize Report"
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    env:
      REPO_URL: ${{ needs.fetch_repo_url.outputs.repoUrl }}
    
    steps:
      - name: ✏️ Create analysis report files
        if: always()
        run: |
          mkdir output
          cd output
          touch README.md
          echo "# 🧪 Repository Analysis Report" >> README.md
          echo "" >> README.md
          echo "## 🏷️ Metadata" >> README.md
          echo "" >> README.md
          echo "Repository:" >> README.md
          echo '[${{ env.REPO_URL }}](https://github.com/${{ env.REPO_URL }})' >> README.md
          echo "" >> README.md
          echo "Analysis Date:" >> README.md
          date >> README.md
          echo "" >> README.md
          echo "---" >> README.md
          echo "" >> README.md
          echo "## [🛡️ Security Scan](./security)" >> README.md
          echo "" >> README.md
          echo "" >> README.md
          echo "## [🚫 Typo Scan](./typos)" >> README.md
          echo "" >> README.md
          echo "" >> README.md
          cd ..

      - name: ⬇️ Download security scan results
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: security
          path: security
          
      - name: ⬇️ Download typo scan results
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: typos
          path: typos

      - name: 🚚 Move scan results into output folder
        if: always()
        run: |
          cd output
          mkdir security
          mkdir typos
          cd ..
          [ -d "./security" ] && cp -a ./security/. output/security || true
          [ -d "./typos" ] && cp -a ./typos/. output/typos || true
      
      - name: 📝 Add job summary output
        run: |
          echo "# 🧪 Repository Analyzed" >> README.md
          echo "" >> README.md
          echo "## 🏷️ Metadata" >> $GITHUB_STEP_SUMMARY
          echo "" >> README.md
          echo "Repository:" >> $GITHUB_STEP_SUMMARY
          echo '[${{ env.REPO_URL }}](https://github.com/${{ env.REPO_URL }})' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Analysis Date:" >> README.md
          echo "" >> $GITHUB_STEP_SUMMARY
          date >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
      - name: 🚚 Push report to store repository
        if: always() && ${{ needs.security_scan.result == 'success' || needs.typo_scan.result == 'success' }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          source-directory: output
          destination-github-username: spencerlepine
          destination-repository-name: ${{ secrets.CONTRIBUTION_STORE_REPO }}
          target-directory: ${{ env.REPO_URL }}
          user-email: spencerlepine26@gmail.com
          target-branch: main
          
  email_notification:
    needs: [fetch_repo_url, security_scan, typo_scan, finalize_report]
    name: "🔔 Send Email Notification"
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    env:
      REPO_URL: ${{ needs.fetch_repo_url.outputs.repoUrl }}
      
    steps:
      - name: 🔊 Send conditional failure mail
        if: ${{ (needs.security_scan.result == 'failure' && needs.typo_scan.result == 'failure') || needs.finalize_report.result == 'failure' }}
        uses: dawidd6/action-send-mail@v3.7.0
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ❌ (FAILURE) Analysis workflow - (${{ env.REPO_URL }})
          # email body as text
          body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} - for repository (${{ env.REPO_URL }})
          # comma-separated string, send email to
          to: spencerlepine26@gmail.com
          # from email name
          from: SpencerBot

      - name: 🔊 Send conditional success mail
        if: ${{ (needs.security_scan.result == 'success' || needs.typo_scan.result == 'success') && needs.finalize_report.result == 'success' }}
        uses: dawidd6/action-send-mail@v3.7.0
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: 🎉 (NEW) Repository Analysis Success - "${{ env.REPO_URL }}"
          # email body as text
          body: (${{ env.REPO_URL }}) => view analysis details - https://github.com/spencerlepine/${{ secrets.CONTRIBUTION_STORE_REPO }}/tree/main/${{ env.REPO_URL }}
          # comma-separated string, send email to
          to: spencerlepine26@gmail.com
          # from email name
          from: SpencerBot
